### ISSUE TITLE
Worker that executes every X seconds 

### ISSUE THREAD

**Issue by GitStorageOne** [mr-highball/ezthreads#6]
Hello!

What is the best way to implement background worker, that will execute some method every 30 seconds?  
And how to terminate worker by force when app closing?

**Comment by mr-highball** [comment]
@GitStorageOne There's a lot of way to do this but one way could be to use an `IEZThreadPool` to queue up some work on an interval. I put together a simple console example showing a method we define to help out making the pool do this (queue up work, initialize settings etc...). 

```pascal
program issue_6;

{$modeswitch nestedprocvars}

uses
  SysUtils,
  ezthreads,
  ezthreads.pool;


var
  LPool : IEZThreadPool;
  LStopWorking : Boolean;
  I : Integer;

  (*
    this is the method that will be performed every x seconds
  *)
  procedure WorkerMethod(const AThread : IEZThread);
  begin
    Inc(I);
    WriteLn('finished working ' + IntToStr(I) + ' times');
  end;

  (*
    uses a thread pool with two workers,
      1.) queues a method every x seconds
      2.) works the method
  *)
  function ThreadPoolMethod(const AInterval : Integer; const AForceStop : Boolean) : IEZThreadPool;

    procedure IntervalMethod(const AThread : IEZThread);
    begin
      while not LStopWorking do
      begin
        LPool.Queue(@WorkerMethod, nil, nil);

        //interval in seconds, but sleep needs msecs
        Sleep(AThread['interval'] * 1000);
      end;

      WriteLn('stopped working');
    end;

  begin
    I := 0;
    LStopWorking := False;

    //setup a thread pool with two workers
    Result := NewEZThreadPool(2);

    //initialize the pool
    Result
      .Queue(@IntervalMethod, nil, nil)
      .AddArg('interval', AInterval)
      .Settings
        .UpdateForceTerminate(AForceStop); //use the force stop argument
  end;

begin
  //call our method with an interval and whether or not to forcefully stop
  //it's recommended to not force stop, but this shows it can be done
  LPool := ThreadPoolMethod(1, False);

  //starts working
  LPool.Start;

  //this section would be where you could wait for console input, form close,
  //or any "terminating" event in order to set the stop working variable to
  //"true" and to call pool.stop()
  while True do
    Sleep(1);

  //stops working. if forceful termination this will be immediate, but otherwise
  //will wait until the worker thread sees the request to stop
  LStopWorking := True;
  LPool.Stop;
end.
```

This may be a bit overkill for what your looking at doing, so an alternative could just be to use a TTimer, set your interval, then queue some work to the pool, but without knowing too much about your constraints I wasn't sure what direction you wanted to go. 

The thread pool itself might also be more than what you're wanting to do, so a standard ezthread could be setup pretty easily

```pascal
LThread := NewEZThread;
LThread.Setup(AMethod).AddArg('interval', 30).Start;
```
where a method might look something like this,
```pascal
procedure AMethod(const AThread);
begin
  Sleep(AThread['interval'] * 1000);
  
  //do work, call methods etc...
  //...
end;
```

Hope this helps, if it answers the question for you just close the issue, otherwise I can see about helping out further 
cheers 🍻 ,
-Highball

**Comment by GitStorageOne** [comment]
Seems, there are memory leaks in first example with pool.
[pool.zip](https://github.com/mr-highball/ezthreads/files/4917770/pool.zip)
[memory-leak.log](https://github.com/mr-highball/ezthreads/files/4917756/memory-leak.log)

Also i get AV sometimes.  
To reproduce, start app, wait few seconds and press enter (ReadLn will be processed and app will try to close)

**Comment by mr-highball** [comment]
I'm not at a computer at the moment to check but put an `Await(LPool)` right after the call to Stop().
If that still produces AV's let me know but I'll try to check sometime today.

**Comment by GitStorageOne** [comment]
Well, that still produce error:

```
  LStopWorking := True;
  LPool.Stop;
  Await(LPool);
```

```
  //LStopWorking := True;
  LPool.Stop;
  //Await(LPool); 
```

This code does not produce error, but still there are memory leaks:

```
  LStopWorking := True;
  //LPool.Stop;
  Await(LPool);
```

**Comment by mr-highball** [comment]
@GitStorageOne Workers appear to be holding a reference to the pool which is preventing it from freeing
![image](https://user-images.githubusercontent.com/35942565/87610260-e96eb580-c6d2-11ea-9709-69f8cd4bdd52.png)

when performing the manual release for each worker everything frees appropriately
![image](https://user-images.githubusercontent.com/35942565/87610445-5bdf9580-c6d3-11ea-9a23-4dc87a945d1b.png)

I've made #7 to track the fix and will report back to this issue when it's all resolved. thanks for reporting this 👍

**Comment by mr-highball** [comment]
@GitStorageOne I believe #7 has been addressed so if you pull latest you should no longer see access violations & memory leaks. If this does resolve this on your end, just close the issue otherwise I may need to look further into what's going on for you

**Comment by GitStorageOne** [comment]
Updated library files from git.  
Well, now that works:

```
  LStopWorking := True;
  Await(LPool);
```

But how to stop threads by force?  
This will freeze application (and cpu will go up):  

```
  // LStopWorking := True;
  LPool.Stop;
  // Await(LPool);
```

And one more question.  
I'm starting app, and see messages like that, everything ok so far:  
![image](https://user-images.githubusercontent.com/3978064/88515373-4849fe00-cff4-11ea-9045-a7a633aa01f8.png)

Now if click inside window, application will freeze:  
![image](https://user-images.githubusercontent.com/3978064/88515603-9f4fd300-cff4-11ea-94a3-6a38bd0f6140.png)

**Comment by mr-highball** [comment]
Hell @GitStorageOne, the blocking being done when you click into the console _appears_ to be either built into `WriteLn` or into the system console itself. I've reproduced this behavior on windows, but also verified that it seems to be blocking the `WriteLn` call when a user does this. It requires "two" key presses to bypass the click, and a `ReadLn`.
```Pascal
procedure TestReadLn;
var
  LThread: IEZThread;

  procedure Start(const AThread : IEZThread);
  var
    I: Integer;
  begin
    I := 0;

    while True do
    begin
      WriteLn('test', I);
      Inc(I);
      Sleep(1000);
    end;
  end;

begin
  LThread := NewEZThread;
  LThread.Setup(Start).Settings.UpdateForceTerminate(True).Thread.Start;
  ReadLn; //if you click in here it takes 2 readlns to pass
  LThread.Stop;
  ReadLn;
end;
```
Also, this small sample shows the force terminate setting that can be used. In this case, the call to `LThread.Stop` would forceful kill the underlying this thread. This was also demonstrated in the earlier sample but abstracted a little bit with the call to `ThreadPoolMethod`
```pascal
 begin
   //...
    //initialize the pool
    Result
      .Queue(@IntervalMethod, nil, nil)
      .AddArg('interval', AInterval)
      .Settings
        .UpdateForceTerminate(AForceStop); //use the force stop argument
  end;

begin
  //call our method with an interval and whether or not to forcefully stop
  //it's recommended to not force stop, but this shows it can be done
  LPool := ThreadPoolMethod(1, False);
```
The caveat is that when I wrote this little sample to test, I've found a bug in the forceful termination code which I've made a new issue for at #9 so I will fix this and report back (I already see the issue so it shouldn't take so long this time)

**Comment by mr-highball** [comment]
@GitStorageOne #9 has been addressed, so now the code you have written should work with one minor tweak (see conditional logic to use await or Lpool.stop)
```pascal
program project1;

{$mode objfpc}{$H+}
{$modeswitch nestedprocvars}

uses
 {$IFDEF UNIX}
 {$IFDEF UseCThreads}
  cthreads,
 {$ENDIF}
 {$ENDIF}
  Classes,
  SysUtils,
  ezthreads,
  ezthreads.pool;

var
  LPool: IEZThreadPool;
  LStopWorking: boolean = false;
  LForceStop: Boolean = false;
  I: integer;

  (*
    this is the method that will be performed every x seconds
  *)
  procedure WorkerMethod(const AThread: IEZThread);
  begin
    Inc(I);
    WriteLn('finished working ' + IntToStr(I) + ' times');
  end;

  (*
    uses a thread pool with two workers,
      1.) queues a method every x seconds
      2.) works the method
  *)
  function ThreadPoolMethod(constref AInterval: integer; constref AForceStop: boolean): IEZThreadPool;

    procedure IntervalMethod(const AThread: IEZThread);
    begin
      while not LStopWorking do
       begin
        LPool.Queue(@WorkerMethod, nil, nil);

        //interval in seconds, but sleep needs msecs
        Sleep(AThread['interval'] * 1000);
       end;

      WriteLn('stopped working');
    end;

  begin
    I := 0;
    LStopWorking := False;

    //setup a thread pool with two workers
    Result := NewEZThreadPool(2);

    //initialize the pool
    Result
      .Queue(@IntervalMethod, nil, nil)
      .AddArg('interval', AInterval)
      .Settings
      .UpdateForceTerminate(AForceStop); //use the force stop argument
  end;

begin
  {$IF DECLARED(GlobalSkipIfNoLeaks)}
  GlobalSkipIfNoLeaks := True;
  setHeapTraceOutput('memory-leak.log');
  {$ENDIF}
  // Force stop
  LForceStop := True;

  //call our method with an interval and whether or not to forcefully stop
  //it's recommended to not force stop, but this shows it can be done
  LPool := ThreadPoolMethod(1, LForceStop);

  //starts working
  LPool.Start;

  //this section would be where you could wait for console input, form close,
  //or any "terminating" event in order to set the stop working variable to
  //"true" and to call pool.stop()
  readln;
  
  //use stop instead of await() here when force stopping
  if LForceStop then
    LPool.Stop
  //otherwise, wait for work to finish
  else
    Await(LPool);
end.
```

**Comment by GitStorageOne** [comment]
I still get issue with force termination.  
Compiled code above, when i press enter, application freezes with high cpu usage.  

Here is compiled exe and source. So, if you compile this code, then everything ok?  
Which version of FPC you use?    
[pool.zip](https://github.com/mr-highball/ezthreads/files/5014826/pool.zip)

**Comment by mr-highball** [comment]
I think this scenario has uncovered a race condition for acquiring locks. I'm tracing this down and will report back. sorry for the back and forth

**Comment by GitStorageOne** [comment]
> I think this scenario has uncovered a race condition for acquiring locks. I'm tracing this down and will report back. sorry for the back and forth

On my PC and FPC 3.2.0. described above issue is stable reproducible.

**Comment by mr-highball** [comment]
@GitStorageOne believe I narrowed this down (thought it was something more involved) and pushed a hotfix. When doing working for #9 I forgot to pass along the force terminate to the workers. After making this change I tested against your project and as soon as the readln is triggered the terminal window closes rather than stalling out

**Comment by GitStorageOne** [comment]
Well, bad news here.  
There are memory leaks...  
And still does not work with `LForceStop := False;`

**Comment by mr-highball** [comment]
I believe the memory leaks are reported due to the fact that the threads are being killed, not due to the library,
https://forum.lazarus.freepascal.org/index.php?topic=35297.15

However... I got a little too focused on the force terminate, that I failed to test the other side 🤦 
Again, sorry for the back and forth, thread pools are a relatively new addition to the library, so I apparently haven't worked out all the _quirks_ yet. I'll report back soon

**Comment by mr-highball** [comment]
@GitStorageOne just noticed something with the project that when using Await, we need to tell the interval worker to stop 
```pascal
// Use stop instead of await() here when force stopping
  if LForceStop then
    LPool.Stop
  // Otherwise, wait for work to finish
  else
  begin
    LStopWorking := True;
    Await(LPool);
  end;
```
